# Generated by Django 4.2.3 on 2023-07-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlinfo',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('longUrl', models.CharField(max_length=150)),
                ('shortUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
