# Generated by Django 4.2.3 on 2023-07-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinfo',
            name='uuid',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
