# Generated by Django 4.2.3 on 2023-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_urls', '0002_alter_urlinfo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinfo',
            name='longUrl',
            field=models.CharField(max_length=300),
        ),
    ]
